######################################################################
# Automatically generated by qmake (3.0) ?? 4? 30 22:31:04 2016
######################################################################

TEMPLATE = app
TARGET = FramelessWindow
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += MainDialog.h
SOURCES += appMain.cpp MainDialog.cpp
